# Generated by Django 4.2.10 on 2024-05-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapp', '0002_rename_content_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='schoolapp.order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
