version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=deni
      - POSTGRES_PASSWORD=deni
      - POSTGRES_DB=deni
    ports:
      - 5432:5432

volumes:
  postgres_data:
